### ISSUE TITLE
LiteStep on 4k

### ISSUE THREAD

**Issue by brembs** [alur/litestep-experimental#2]
Not sure anyone is still following this repo...
Anyway, I've been using LS since b23 on win95 (now for a long time already on all my win10 machines) :-) Today I've changed to a 4k monitor and for the first time LS is behaving very weird: it behaves as if the screen resolution still is my old one, e.g., if I center my background wallpaper, only the central, part of it shows (I use nDesk) and all LS labels, shortcuts and wharfs, etc. appear where they used to appear on the old screen in the same size as on the old screen. However, if I check screen resolution, it says 4k. If I quit LS, my wallpaper shows the full 4k but the utility that reports screen resolution hasn't changed. I've disabled all modules one at a time, but the behavior persists, so I think it's some core part of LS. There are no .rc or .ini files where the screen resolutions or desktop size is explicitly set. Is it set implicitly somewhere?

Many thanks for any help!

Bjoern

**Comment by alur** [comment]
Per our email thread, I think I fixed this in https://github.com/lsdev/LiteStep/commit/25271b7cfc116510b43b2daa5d47e9e05c6c0252

It just isn't in any of the 0.25.0 alpha releases yet.
